repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
<<<<<<< HEAD
    rev: v1.30.0
=======
    rev: v1.39.0
>>>>>>> upstream/master
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_validate
      #- id: terraform_tflint
      #- id: terragrunt_fmt
  - repo: git://github.com/pre-commit/pre-commit-hooks
<<<<<<< HEAD
    rev: v3.0.1
=======
    rev: v3.2.0
>>>>>>> upstream/master
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
