version: '3.4'
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - HOSTNAME_EXTERNAL=localstack
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
  go:
    build:
      context: .
      dockerfile: Dockerfile.go+terraform
    command: >
        bash -c "cd /code/test/ && go test"
    volumes:
      - .:/code
    depends_on:
      - localstack
