version: '3.4'
services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=IAM
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localstack
  go:
    build:
      context: .
      dockerfile: Dockerfile.go+terraform
    command: >
        bash -c "cd /code/test/ && ../wait-for-it.sh localstack:4593 -- go test"
    volumes:
      - .:/code
    depends_on:
      - localstack
