version: 2

commands:
  terraform-install:
    description: "Install Terraform"
    parameters:
      version:
        type: string
        default: "0.12.24"
    steps:
      - run:
          command: |
            apt-get update && apt-get install -y unzip
            set -eu;
            if ! [ -x "$(command -v terraform)" ]; then
              wget -O /tmp/terraform.zip https://releases.hashicorp.com/terraform/<< parameters.version >>/terraform_<< parameters.version >>_linux_amd64.zip \
              && unzip /tmp/terraform.zip -d /usr/local/bin;
            fi;

jobs:
  validate:
    docker:
      - image: hashicorp/terraform:0.12.25
    steps:
      - checkout
      - run:
          name: terraform init
          command: find . -type f -name "*.tf" -exec dirname {} \;|sort -u | while read m; do (cd "$m" && terraform init -input=false -backend=false) || exit 1; done
      - run:
          name: Validate Terraform configurations
          command: find . -name ".terraform" -prune -o -type f -name "*.tf" -exec dirname {} \;|sort -u | while read m; do (cd "$m" && terraform validate && echo "√ $m") || exit 1 ; done
          environment:
            AWS_DEFAULT_REGION: us-east-1
      - run:
          name: Check if Terraform configurations are properly formatted
          command: if [[ -n "$(terraform fmt -write=false)" ]]; then echo "Some terraform files need be formatted, run 'terraform fmt' to fix"; exit 1; fi
      - run:
          name: Install tflint
          command: wget -O /tmp/tflint.zip https://github.com/wata727/tflint/releases/download/v0.12.1/tflint_linux_amd64.zip && unzip /tmp/tflint.zip -d /usr/local/bin
      - run:
          name: Check Terraform configurations with tflint
          command: tflint
  terratest:
    docker:
      - image: circleci/golang:1.14.1-stretch
      - image: localstack/localstack:latest
    steps:
      - checkout
      - terraform-install
      - run:
          name: Go test
          command: |
            cd /code/test/ \
            && go test

workflows:
  version: 2
  build:
    jobs:
      - validate
      - terratest
