style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/youse-seguradora/terraform-aws-iam
options:
  header:
    pattern: "^(.*)$"
    pattern_maps:
      - Subject
